### ISSUE TITLE
turing machine jpeg issue

### ISSUE THREAD

**Issue by Charlie-Beard** [pratikthanki/pratikthanki.github.io#12]
Hey there,

Just wanted to double-check if this diagram is correct? 

I think there may be couple of issues:

1.  at q6 the first set of _a_ before the # is zero. zero is an even number. I think q6 should go on to validate the number of _a_ after the # is also even
2. the transition from q5 to accept. shouldn't this be an empty symbol instead of a # ? 

![image](https://user-images.githubusercontent.com/38183582/146678207-75522ac7-a1d2-494f-a7c5-a4a1af211e1c.png)

**Comment by pratikthanki** [comment]
Hey @Charlie-Beard - sorry for the late reply I just noted this! 

To answer your questions:
1. On second look yeah that's correct. q6 should be an accept state, 0 has the same parity as 0
2. And yes we can denote this as `#` or an implicit empty string `⊔`
